name: pull-request
on:
  pull_request:
    branches: [ main ]
jobs:
  integration-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up node 
        uses: actions/setup-node@v1 
        with:
          node-version: ${{ matrix.node_version }}
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/yarn.json') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test 
